# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kostya Zolotarov
email: kostya.zolotarov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open Source Projects, Source Code, Publications, Blog, Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kz9676.github.io" # the base hostname & protocol for your site
twitter_username: kz9676
github_username:  kz9676

# Build settings
markdown: kramdown
